version: "2"
services:
  # Backend
  server:
    container_name: server
    build: ./
    command: yarn dev
    ports:
      - 3001:3001
    volumes:
      - .:/app
    restart: unless-stopped
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "bridge-applications-local"
